### ISSUE TITLE
Broken link on API Gateway getting started example rest API

### ISSUE THREAD

**Issue by bwvoss** [ngrok/ngrok-docs#1028]
On this page: https://github.com/ngrok/ngrok-docs/blob/main/docs/guides/api-gateway/get-started.mdx

The link to the [the sample API](https://github.com/ngrok-samples/ngrok-rest-api) is broken.  The repository doesn't seem to exist in either the ngrok or ngrok-samples orgs.

**Comment by joelhans** [comment]
Hi @bwvoss! Thanks for reporting this. The link was OK, but we missed the fact that the repo was private. We've set its visibility to public, so this should be working now—let us know if you continue to have issues!
