### ISSUE TITLE
Typo in Zero-Knowledge TLS image

### ISSUE THREAD

**Issue by refeed** [ngrok/ngrok-docs#126]
![image](https://user-images.githubusercontent.com/20320125/206911491-897488dc-0c60-4074-b27f-5ebc0f14ab54.png)

"termincation" should be termination

https://ngrok.com/docs/cloud-edge/zero-knowledge-tls

**Comment by sudobinbash** [comment]
Nice catch @refeed ! I'll fix the image.

**Comment by russorat** [comment]
sorry for the delay! thank you for opening this!
