### ISSUE TITLE
Do we support environment variables in the CLI? If not, remove this

### ISSUE THREAD

**Issue by sudobinbash** [ngrok/ngrok-docs#187]
Support for environment variables is listed in the doc:

https://github.com/ngrok/ngrok-docs/blob/main/docs/ngrok-agent/index.md#supported-env-variables

However, the ngrok cli doesn't seem to support these variables.

**Comment by russorat** [comment]
We support NGROK_AUTHTOKEN (it's used for docker), but not NGROK_API_KEY it seems.
