### ISSUE TITLE
request-header-add not working

### ISSUE THREAD

**Issue by Jowen0** [ngrok/ngrok-docs#396]
I want to add request header like this:
```
ngrok http 8080 --request-header-add 'ngrok-skip-browser-warning:100'
```
But, it not working

**Comment by inconshreveable** [comment]
can you please describe the behavior you're expecting to see and then describe the behavior you're seeing instead?

**Comment by Jowen0** [comment]
I want to free-pass for visite site page when i access ngrok end point,
Visite Site page introduce methods to pass its page, one of  them is add request header 'ngrok-skip-browser-warning' with any value

**Comment by inconshreveable** [comment]
you cannot use ngrok's own request header modification functionality to bypass the browser warning.

we'll add a note about this to the documentation. thank you!

**Comment by Jowen0** [comment]
@inconshreveable 
Thanks for your fast answer :)
Oh, i can't find. it how can i see it?
