### ISSUE TITLE
Typo in free static domain blog post

### ISSUE THREAD

**Issue by BrainCrumbz** [ngrok/ngrok-docs#413]
Hi all

not sure this is the right place where to post this, could not find anything closer. Please, point us in the right direction if needed.

In blog post showing this new feature of free static domains ([link](https://ngrok.com/blog-post/free-static-domains-ngrok-users)) there's a bit of code that can be copy-pasted in order to run ngrok with a new domain:

![immagine](https://github.com/ngrok/ngrok-docs/assets/3185573/1270d181-5f42-499a-b972-aca05d16d185)

There's an almost invisible typo in there, that will give you error when you run pasted command: the second dash before the word `domain` is not a regular dash.

HTH

**Comment by russorat** [comment]
@BrainCrumbz thanks for the issue! i'm getting it fixed right now.

**Comment by russorat** [comment]
this should be fixed now. thanks again!
