### ISSUE TITLE
Add 'us-cal-1' to Agent CLI and Agent Config File Reference Docs

### ISSUE THREAD

**Issue by shubcodes** [ngrok/ngrok-docs#417]
--region flag is missing region 'us-cal-1' in both the CLI and Config File Reference Docs

CONFIG FILE: 
https://github.com/ngrok/ngrok-docs/blob/main/docs/secure-tunnels/ngrok-agent/reference/config.md#region

CLI: 
https://github.com/ngrok/ngrok-docs/blob/main/docs/secure-tunnels/ngrok-agent/reference/ngrok.md

**Comment by nijikokun** [comment]
I've added it to the config file location in #426, it's been added to cloud-edges in #415, the CLI is auto-generated and that should come later.
