### ISSUE TITLE
I can't sign up ngrok on my phone

### ISSUE THREAD

**Issue by Focus901** [ngrok/ngrok-docs#441]

**Comment by inconshreveable** [comment]
thank you for the report! can you send us additional details about your phone's make and model? as well as the browser that you're using? lastly, screenshots of the errors you're encountering would be helpful as well.

thank you!

**Comment by euank** [comment]
I couldn't reproduce this with a recent version of mobile firefox.
Please feel free to re-open this or message support with additional information on what errors you hit and how to reproduce em!
