### ISSUE TITLE
Document Certificate Issuer option for Custom Agent Ingresses

### ISSUE THREAD

**Issue by jrobsonchase** [ngrok/ngrok-docs#484]
Rough description of the feature in need of wordsmithing:

---

* Two certificate issuer options, `ngrok`'s internal CA and Let's Encrypt
* Selected via a dropdown at custom ingress creation time:
![2023-11-14-135257_462x278_scrot](https://github.com/ngrok/ngrok-docs/assets/1553581/9fe237a0-610a-4067-84cb-99d74134d9d9)
* `ngrok` details:
  * This is the default - automatically trusted by the agent
  * Provisioned immediately
  * May require additional configuration if an outbound proxy sits between the agent and ngrok for deep traffic inspection, since the proxy won't automatically trust the ngrok-issued certificate.
* Let's Encrypt details:
  * _not_ automatically trusted by the agent, requires the `root_cas` option to be set to `host` (or the Let's Encrypt root cert) in the configuration file (assuming the host trusts the standard set of public CAs). Same goes for any SDKs or other agent-like things.
  * _not_ immediately provisioned - blocked on DNS delegation and the propagation thereof. Could take up to 48h if propagation is slow. An ngrok certificate is provisioned and used in the meantime. Note that even if the DNS "Check Status" succeeds in the ngrok dashboard, it may not have propagated to Let's Encrypt yet. 
  * Useful if getting an outbound proxy to trust the `ngrok` CA is challenging due to either technical or organizational constraints.

If Let's Encrypt is selected, the agent ingress drawer will show this card while the certificate is provisioning:

![2023-11-14-134132_590x162_scrot](https://github.com/ngrok/ngrok-docs/assets/1553581/4091b17a-f6c7-4018-99ff-007c1fd9ace0)

Once it finishes, the certificate will be used by the custom agent ingress instead of the `ngrok`-issued one.

---

Happy to help with the smithing and add any clarifying context here!

**Comment by CK-Ward** [comment]
@nijikokun @pshafton Here are docs on how to use public ingress certs

**Comment by pshafton** [comment]
@salilsub do we want to try to get this information into the docs for Custom Agent Ingress.
