### ISSUE TITLE
Use Google Tag Manager

### ISSUE THREAD

**Issue by sudobinbash** [ngrok/ngrok-docs#51]
Use the Google Tag Manager used by ngrok.com.

- Our tag manager loads JS (from Olark and Hubspot) in the page without requiring us to update our site.
- Our tag works on ngrok.com and the current /docs
- When we try to load the same thing on docusaurus, the Tag Manager is loaded, but the nested JS not.

To reproduce:

1. Change `docusaurus.config.js` with our tag manager id:

    <img width="622" alt="image" src="https://user-images.githubusercontent.com/8906839/197879219-4a2a419a-90e7-4060-ace1-65853f2fcb96.png">

2. Build and then run the site preview ([according to Docusaurus](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag), tag manager runs only in production builds)

```
npm run build
npm run serve 
```

**Comment by russorat** [comment]
done
