### ISSUE TITLE
SEO: Page has links to broken URLs

### ISSUE THREAD

**Issue by blyonng** [ngrok/ngrok-docs#724]
The following spreadsheet has a list of pages with content that links to URLs with a 4xx status code.

https://docs.google.com/spreadsheets/d/1muMvNuDORYbKffWiKQWrU4nxGj0-ebWVKGT_0ofmOcA/edit?usp=sharing

Suggested solution:

* Edit the content to either replace the URLs or remove them.

**Comment by salilsub** [comment]
@blyonng Some of these links point to dashboard pages which are valid, but require authentication. Removing them is not practical since we need to point customers to those links. Is there a way we could keep the links without impacting SEO?

**Comment by blyonng** [comment]
> @blyonng Some of these links point to dashboard pages which are valid, but require authentication. Removing them is not practical since we need to point customers to those links. Is there a way we could keep the links without impacting SEO?

@salilsub good question. There are typically two options.

1. Add a `rel="nofollow"` attribute to the HTML anchor tag for the impacted hyperlinks.
2. Add a logged out version of the authentication page that doesn't result in an error.

Given the effort involved, I suggest the first option. In the long run, the second option might be helpful from a UX perspective, but it doesn't feel it's necessary at this time.
