### ISSUE TITLE
Fix typo for Hygraph in webhook verification modules documentation

### ISSUE THREAD

**Issue by akclaireshaw** [ngrok/ngrok-docs#81]
Hygraph is listed [here](https://ngrok.com/docs/cloud-edge/modules/webhook) as "GraphCMS (Formerly Hygraph)", it should be "Hygraph (formerly GraphCMS)".

<img width="616" alt="Screen Shot 2022-11-03 at 1 04 22 PM" src="https://user-images.githubusercontent.com/111439719/199787389-01dab475-273d-4429-99fe-41a4d4eb4666.png">

**Comment by russorat** [comment]
fixed in #120
