### ISSUE TITLE
"ngrokAPICommon" section appears to be missing from the docs

### ISSUE THREAD

**Issue by justngrok** [ngrok/ngrok-docs#885]
[ngrokAPICommon](https://ngrok.com/docs/k8s/crds/#ngrokapicommon) links go nowhere on the k8s CRDs. The "ngrokAPICommon" section appears to be missing from the docs.

https://ngrok.com/docs/k8s/crds/

**Comment by jonstacks** [comment]
Fixed by https://github.com/ngrok/ngrok-docs/pull/896
