### ISSUE TITLE
Docs 404 page appears broken

### ISSUE THREAD

**Issue by blyonng** [ngrok/ngrok-docs#951]
Steps to reproduce:

1. Navigate to a 404 URL, such as https://ngrok.com/docs/asdf

Observed:

1. See screenshot.

Expected:

1. Something pretty, or at least more intelligible.

<img width="1861" alt="Screenshot 2024-09-23 at 12 05 17 PM" src="https://github.com/user-attachments/assets/9b1c9719-0c60-4bb7-af44-980855df26b6">

**Comment by foundanand** [comment]
This has been fixed I guess

**Comment by foundanand** [comment]
Now if you visit that page it shows this 
![image](https://github.com/user-attachments/assets/1b599182-8503-4c8c-bbf6-bd4d933a36c4)

**Comment by blyonng** [comment]
Closing as fixed
